site_name: Ketting
site_url: https://kwatman.github.io/Ketting/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
  icon:
    admonition:
      api: material/api

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
